### ISSUE TITLE
missing .babelrc can cause the build to not work.

### ISSUE THREAD

**Issue by Pixelatex** [Jobeir/styled-components-server-side-rendering#1]
I was trying out your tutorial and noticed that it didn't build. Adding the babelrc file did fix it and after looking it up.

Babel will look for a rc file, and if none are found, will travel up the library to find one. Most likely, babel was picking a rc file from a different file somewhere.

Maybe add the .babelrc file to the tutorial?

**Comment by brotzky** [comment]
@Pixelatex my bad. I'll add that in tonight or over the weekend.

**Comment by brotzky** [comment]
I've added a note in the tutorial to add a `.babelrc` if there's an issue
