### ISSUE TITLE
why the setTimeout and onClick don't work on this project?

### ISSUE THREAD

**Issue by huiyuye** [Jobeir/styled-components-server-side-rendering#5]
Hello guy. I add setTimeout and onClick to react on this project,  but it don't work 

 Can you help me? thank you so much!

**Comment by brotzky** [comment]
You're trying to access the `window` on the server. You don't have access to browser APIs on the server, so you have to set them when your componentDidMount

**Comment by huiyuye** [comment]
Could you tell me how to set them on componentDidMount ? I try to check the solution on google but have not.

**Comment by brotzky** [comment]
@huiyuye I'd need more context. Could you share a Codesandbox of what you're trying to achieve?
